<?php
/**
 * Byblio
 * Useraccount, Login view
 * for user resetting password
 * @copyright 2013 Byblio.com
 * @author: Paul A. Oliver
 *
 */
	
	// app service manager
	$sm = $this->getHelperPluginManager()->getServiceLocator();
	
	// css core folder
	$css_coreFolder = $sm->get('css_coreFolder');
	
	// style sheets
	$cssPath = $this->basePath(PUBLIC_FOLDER) . "/css/" .$css_coreFolder ."/useraccount/useraccount.1.0.css";
	$this->headLink()->appendStylesheet($cssPath);
	
	
	// login form
	$loginFormAll = $this->loginAllInfo;
		
	if(is_array($loginFormAll)){
		// form (no captcha)
		$loginForm = null;
		if(key_exists('form', $loginFormAll)){
			$loginForm = $loginFormAll['form'];
		}
		// form (captcha)
		$loginFormCaptcha = null;
		if(key_exists('formCaptcha', $loginFormAll)){
			$loginFormCaptcha = $loginFormAll['formCaptcha'];
		}
		// info
		$loginInfo = array();
		if(key_exists('info', $loginFormAll)){
			$loginInfo = $loginFormAll['info'];
		}
	
		// submitted?
		$formSubmitted = false;
		if(key_exists('formSubmitted', $loginInfo)){
			$formSubmitted = $loginInfo['formSubmitted'];
		}
		
	
		// login form html
		$loginFormHTML = $this->partial('loginForm', array('formNoCaptcha'=>$loginForm, 'formCaptcha'=>$loginFormCaptcha, 'loginInfo'=>$loginInfo));
		 
	}
	
?>

<div class="login">
	<div class="pageTitle"><?php echo $this->translate('Hello')?></div>

	<div class="pageBorder">
	
		<div class="col_1"><!-- log in form -->
				<div class="intro">
					<h2><?php echo $this->translate('Log in')?></h2>
					<p><?php echo $this->translate('Please log in to view the page you are looking for.');?></p>
				</div>
				
				<div class="form">
					<?php 
						// login form
						echo $loginFormHTML;
					?>
				</div>
			
				<div class="info">
					<p><?php echo $this->translate('Alternatively...')?></p>					
					
					<div class="links">
						<div class="link_goto">
			   				<a href="<?php echo $this->url('signup');?>"><?php echo $this->translate('I\'m not registered - let me sign up!');?></a>
			   			</div>
			   			
						<div class="link_goto">
			   				<a href="<?php echo $this->url('home');?>"><?php echo $this->translate('Take me to the home page');?></a>
			   			</div>
			   			
			   			<div class="link_goto">
		   					<a href="<?php echo $this->url('library-allPublic');?>"><?php echo $this->translate('Go to the public libraries...');?></a>
		   				</div>
			   			
			   		</div>
				</div>
			</div><!--  end col_1 -->

		<div class="clearFloats"></div>
		
		
		
	</div><!-- end pageBorder -->
</div>